# Generated by Django 5.2.6 on 2025-09-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('warehouse', '0002_rate_shipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='user',
        ),
        migrations.AddField(
            model_name='shipment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.profile'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='suit_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
    ]
