# Generated by Django 5.2.6 on 2025-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_shipment_options_remove_shipment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='suit_number',
            field=models.CharField(max_length=50),
        ),
    ]
