# Generated by Django 5.2.6 on 2025-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_shipment_suit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='suit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
