# Generated by Django 5.2.5 on 2025-09-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_delete_courierchoice'),
        ('warehouse', '0006_shipmentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customer.couriercompany')),
            ],
        ),
        migrations.CreateModel(
            name='courireshipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courireshipment', to='customer.couriercompany')),
            ],
        ),
    ]
