# Generated by Django 5.2.5 on 2025-09-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_couriershipment_courireshipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courireshipment',
            name='courier',
        ),
        migrations.DeleteModel(
            name='CourierShipment',
        ),
        migrations.DeleteModel(
            name='courireshipment',
        ),
    ]
