# Generated by Django 5.2.5 on 2025-09-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_delete_courierchoice'),
        ('warehouse', '0008_remove_courireshipment_courier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_number', models.CharField(max_length=50, unique=True)),
                ('selected_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customer.couriercompany')),
                ('selected_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customer.courierrate')),
            ],
        ),
    ]
