# Generated by Django 5.2.5 on 2025-09-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_shipmentrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentRate',
        ),
    ]
