# Generated by Django 5.2.5 on 2025-09-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_remove_shipment_selected_courier_and_more'),
        ('warehouse', '0010_delete_shipmentrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='selected_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customer.couriercompany'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='selected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='selected_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customer.courierrate'),
        ),
    ]
