# Generated by Django 5.2.5 on 2025-10-01 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_remove_shipment_selected_courier_and_more'),
        ('warehouse', '0011_shipment_selected_courier_shipment_selected_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('chosen_at', models.DateTimeField(auto_now_add=True)),
                ('seen_by_warehouse', models.BooleanField(default=False)),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.couriercompany')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.courierrate')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_selections', to='warehouse.shipment')),
            ],
            options={
                'ordering': ('-chosen_at',),
            },
        ),
    ]
