# Generated by Django 5.2.6 on 2025-10-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_consolidation_consolidationitem'),
        ('warehouse', '0014_courier_alter_courierselection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierselection',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='courierselection',
            old_name='chosen_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='courierselection',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='courierselection',
            name='rate',
        ),
        migrations.AddField(
            model_name='courierselection',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='carrier_rate_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='legacy_courier_company',
            field=models.ForeignKey(blank=True, help_text='Temporary during migration; remove after backfill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selections_legacy', to='customer.couriercompany'),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='legacy_rate',
            field=models.ForeignKey(blank=True, help_text='Temporary during migration; remove after backfill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selections_legacy', to='customer.courierrate'),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='service_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='courierselection',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='customer.profile'),
        ),
    ]
