# Generated by Django 5.2.6 on 2025-10-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_alter_courierselection_legacy_courier_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='selected_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_shipments', to='warehouse.courier'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='selected_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.courierselection'),
        ),
    ]
