# Generated by Django 5.2.6 on 2025-10-04 11:57

from django.db import migrations


def populate_couriers(apps, schema_editor):
    CustomerCourier = apps.get_model('customer', 'Courier')
    WarehouseCourier = apps.get_model('warehouse', 'Courier')
    for c in CustomerCourier.objects.all():
        WarehouseCourier.objects.get_or_create(name=c.name)


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_alter_shipment_selected_courier_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_couriers, migrations.RunPython.noop),
    ]
