# Generated by Django 5.2.6 on 2025-10-06 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_add_created_at_to_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='warehouse.warehouse'),
        ),
    ]
