# Generated by Django 5.2.6 on 2025-10-08 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_country_active_country_api_base_and_more'),
        ('warehouse', '0021_warehouse_address_warehouse_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='height',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='length',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_company',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='width',
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='warehouse.courier'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shipment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Warehouse Accepted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('held', 'Held')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='customer.profile'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='suit_number',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
