# Generated by Django 5.2.6 on 2025-10-08 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_alter_shipment_options_remove_shipment_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
