# Generated by Django 5.2.6 on 2025-10-11 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_alter_shipment_height_cm_alter_shipment_length_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Warehouse Accepted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('held', 'Held'), ('accepted', 'Delivery Accepted'), ('started', 'Delivery Start'), ('completed', 'Delivery Completed')], db_index=True, default='pending', max_length=32),
        ),
    ]
