# Generated by Django 5.2.6 on 2025-10-11 11:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_shipment_status_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cbm', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12)),
                ('total_volume_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('total_gross_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('chargeable_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('rate_per_kg', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidations', to=settings.AUTH_USER_MODEL)),
                ('shipments', models.ManyToManyField(related_name='consolidations', to='warehouse.shipment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
