# Generated by Django 5.2.6 on 2025-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_shipmentconsoleaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shipmentstatushistory',
            index=models.Index(fields=['shipment', 'created_at'], name='warehouse_s_shipmen_c55408_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatushistory',
            index=models.Index(fields=['status'], name='warehouse_s_status_ac8d34_idx'),
        ),
    ]
