# Generated by Django 5.2.6 on 2025-10-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_shipmentstatushistory_warehouse_s_shipmen_c55408_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentConsoleAction',
        ),
    ]
