# Generated by Django 5.2.6 on 2025-10-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_alter_consolidation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
