# Generated by Django 5.2.6 on 2025-09-18 09:14

import customer.models
import customer.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, help_text='Upload a PDF file (max 5 MB).', null=True, upload_to=customer.models.purchase_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), customer.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
