# Generated by Django 5.2.5 on 2025-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_consoleshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoleshipment',
            name='action',
            field=models.CharField(choices=[('hold', 'Hold')], max_length=20),
        ),
    ]
