# Generated by Django 5.2.5 on 2025-09-23 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_consoleshipment_action'),
        ('warehouse', '0006_shipmentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=120)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('min_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='customer.couriercompany')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleShipmentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chargeable_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cbm', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_shipment_rates', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_rates', to='warehouse.shipment')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_rates', to='customer.couriercompany')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_rates', to='customer.rate')),
            ],
            options={
                'verbose_name': 'Console Shipment Rate',
                'verbose_name_plural': 'Console Shipment Rates',
                'ordering': ('-created_at',),
            },
        ),
    ]
