# Generated by Django 5.2.5 on 2025-09-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_couriercompany_rate_consoleshipmentrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoleshipmentrate',
            name='shipment',
        ),
    ]
