# Generated by Django 5.2.5 on 2025-09-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_consoleshipmentrate_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='courier',
        ),
        migrations.DeleteModel(
            name='ConsoleShipmentRate',
        ),
        migrations.DeleteModel(
            name='CourierCompany',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
