# Generated by Django 5.2.5 on 2025-09-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_couriercompany_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='courier',
        ),
        migrations.DeleteModel(
            name='CourierCompany',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
