# Generated by Django 5.2.6 on 2025-09-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_rate_courier_delete_couriercompany_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='courier_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CourierRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_kg', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='customer.couriercompany')),
            ],
        ),
    ]
