# Generated by Django 5.2.6 on 2025-09-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_couriercompany_courierrate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourierRate',
            new_name='cargoRate',
        ),
    ]
