# Generated by Django 5.2.6 on 2025-09-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_courierrate_cargorate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cargoRate',
        ),
        migrations.DeleteModel(
            name='CourierCompany',
        ),
    ]
