# Generated by Django 5.2.5 on 2025-09-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_couriercompany_courierrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriercompany',
            name='logo',
            field=models.ImageField(default='exit', upload_to='logo'),
            preserve_default=False,
        ),
    ]
