# Generated by Django 5.2.5 on 2025-09-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_couriercompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriercompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='courier_logos/'),
        ),
    ]
