# Generated by Django 5.2.5 on 2025-09-25 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_couriercompany_logo'),
        ('warehouse', '0006_shipmentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.couriercompany')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.shipment')),
            ],
        ),
    ]
