# Generated by Django 5.2.5 on 2025-09-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_courierchoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourierChoice',
        ),
    ]
