# Generated by Django 5.2.5 on 2025-09-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_delete_courierchoice'),
        ('warehouse', '0010_delete_shipmentrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierrate',
            name='courier',
        ),
        migrations.DeleteModel(
            name='CourierCompany',
        ),
        migrations.DeleteModel(
            name='CourierRate',
        ),
    ]
