# Generated by Django 5.2.5 on 2025-09-27 12:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_courierrate_courier_delete_couriercompany_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='courier_logos/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CourierRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='customer.couriercompany')),
            ],
            options={
                'ordering': ('courier__name', 'id'),
                'indexes': [models.Index(fields=['active'], name='customer_co_active_da8cd7_idx'), models.Index(fields=['currency'], name='customer_co_currenc_d122e5_idx')],
            },
        ),
    ]
