# Generated by Django 5.2.5 on 2025-09-28 07:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_couriercompany_courierrate'),
        ('warehouse', '0010_delete_shipmentrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('chosen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-chosen_at',),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_number', models.SlugField(max_length=64)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('selected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='couriercompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courierrate',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='courierrate',
            name='customer_co_active_da8cd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='courierrate',
            name='customer_co_currenc_d122e5_idx',
        ),
        migrations.AlterField(
            model_name='couriercompany',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='courierrate',
            name='min_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='courierrate',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='chosen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.couriercompany'),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.courierrate'),
        ),
        migrations.AddField(
            model_name='courierselection',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_selections', to='warehouse.shipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='selected_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customer.couriercompany'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='selected_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customer.courierrate'),
        ),
    ]
