# Generated by Django 5.2.5 on 2025-09-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_courierselection_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierselection',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_selections', to='customer.shipment'),
        ),
    ]
