# Generated by Django 5.2.5 on 2025-09-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_courierselection_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='selected_courier',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='selected_rate',
        ),
        migrations.AlterModelOptions(
            name='couriercompany',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='courierrate',
            options={'ordering': ('courier__name', 'currency', 'id'), 'verbose_name': 'Courier rate', 'verbose_name_plural': 'Courier rates'},
        ),
        migrations.DeleteModel(
            name='CourierSelection',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
