# Generated by Django 5.2.6 on 2025-10-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_address'),
        ('warehouse', '0013_staffnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consoleshipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='consoleshipment',
            name='processed',
        ),
        migrations.AlterField(
            model_name='consoleshipment',
            name='action',
            field=models.CharField(choices=[('hold', 'On Hold'), ('release', 'Released'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=32),
        ),
        migrations.AlterField(
            model_name='consoleshipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='consoleshipment',
            constraint=models.UniqueConstraint(fields=('shipment', 'action'), name='uniq_console_action_per_shipment'),
        ),
    ]
