# Generated by Django 5.2.6 on 2025-10-02 11:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_consoleshipment_options_and_more'),
        ('warehouse', '0014_courier_alter_courierselection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cbm', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('total_volume_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_gross_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('chargeable_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('chargeable_basis', models.CharField(choices=[('gross', 'Gross'), ('volume', 'Volume')], default='volume', max_length=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipments_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='confirmed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsolidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.consolidation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_items', to='warehouse.shipment')),
            ],
            options={
                'indexes': [models.Index(fields=['consolidation'], name='customer_co_consoli_59e7ce_idx'), models.Index(fields=['shipment'], name='customer_co_shipmen_baf46b_idx')],
                'unique_together': {('consolidation', 'shipment')},
            },
        ),
    ]
