# Generated by Django 5.2.6 on 2025-10-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_consolidation_consolidationitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourierCompany',
            new_name='Courier',
        ),
    ]
