# Generated by Django 5.2.6 on 2025-10-04 11:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_alter_address_fields'),
        ('warehouse', '0017_alter_shipment_selected_courier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', 'type', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='consoleshipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Console Shipment Action', 'verbose_name_plural': 'Console Shipment Actions'},
        ),
        migrations.AlterModelOptions(
            name='consolidation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='address',
            name='one_default_address_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='consoleshipment',
            name='uniq_console_action_per_shipment',
        ),
        migrations.AlterUniqueTogether(
            name='consolidationitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='consolidation',
            name='note',
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consoleshipment',
            name='action',
            field=models.CharField(choices=[('hold', 'Hold'), ('release', 'Release'), ('packed', 'Packed'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('problem', 'Problem / Exception'), ('cancelled', 'Cancelled')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='consoleshipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consoleshipment',
            name='note',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='consoleshipment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_entries', to='warehouse.shipment'),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='chargeable_basis',
            field=models.CharField(default='volume', max_length=32),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='chargeable_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='status',
            field=models.CharField(choices=[('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='total_cbm',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='total_gross_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='total_volume_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='consoleshipment',
            index=models.Index(fields=['shipment', 'action'], name='customer_co_shipmen_c991a3_idx'),
        ),
        migrations.AddIndex(
            model_name='consoleshipment',
            index=models.Index(fields=['created_at'], name='customer_co_created_b41e93_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidation',
            index=models.Index(fields=['user', 'created_at'], name='customer_co_user_id_23abf8_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidation',
            index=models.Index(fields=['status'], name='customer_co_status_8146d6_idx'),
        ),
        migrations.AddIndex(
            model_name='courierrate',
            index=models.Index(fields=['courier', 'active'], name='customer_co_courier_b62c80_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'type'), name='uniq_default_address_per_type'),
        ),
        migrations.AddConstraint(
            model_name='consoleshipment',
            constraint=models.UniqueConstraint(fields=('shipment', 'action'), name='uniq_shipment_action'),
        ),
        migrations.AddConstraint(
            model_name='consolidationitem',
            constraint=models.UniqueConstraint(fields=('consolidation', 'shipment'), name='uniq_consolidation_shipment'),
        ),
    ]
