# Generated by Django 5.2.6 on 2025-10-04 13:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_alter_address_options_alter_consoleshipment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gold', max_length=100, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('delivery_days', models.PositiveIntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gold Customer Plan',
                'verbose_name_plural': 'Gold Customer Plans',
            },
        ),
        migrations.CreateModel(
            name='PlatinumCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Platinum', max_length=100, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('delivery_days', models.PositiveIntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platinum Customer Plan',
                'verbose_name_plural': 'Platinum Customer Plans',
            },
        ),
    ]
