# Generated by Django 5.2.6 on 2025-10-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_goldcustomer_platinumcustomer'),
        ('warehouse', '0019_add_created_at_to_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidation',
            name='selected_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_consolidations', to='warehouse.courier'),
        ),
        migrations.AddField(
            model_name='consolidation',
            name='selected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='consolidation',
            name='selected_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_consolidations', to='customer.courierrate'),
        ),
    ]
