# Generated by Django 5.2.6 on 2025-10-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_consolidation_selected_courier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoldCustomer',
        ),
        migrations.DeleteModel(
            name='PlatinumCustomer',
        ),
    ]
