# Generated by Django 5.2.6 on 2025-10-06 14:06

from django.db import migrations
from decimal import Decimal


def seed_tiers(apps, schema_editor):
    MembershipTier = apps.get_model("customer", "MembershipTier")
    MembershipTier.objects.update_or_create(
        name="Silver",
        defaults=dict(
            description="Basic membership with no discounts",
            percent_fee=Decimal("0.00"),
            fixed_fee=Decimal("0.00"),
            currency="USD",
            active=True,
            ordering=5,
        ),
    )
    MembershipTier.objects.update_or_create(
        name="Gold",
        defaults=dict(
            description="Gold membership with 10% discount on shipping",
            percent_fee=Decimal("10.00"),
            fixed_fee=Decimal("0.00"),
            currency="USD",
            active=True,
            ordering=10,
        ),
    )
    MembershipTier.objects.update_or_create(
        name="Platinum",
        defaults=dict(
            description="Platinum membership with 25% discount on shipping",
            percent_fee=Decimal("25.00"),
            fixed_fee=Decimal("0.00"),
            currency="USD",
            active=True,
            ordering=20,
        ),
    )


def unseed_tiers(apps, schema_editor):
    MembershipTier = apps.get_model("customer", "MembershipTier")
    MembershipTier.objects.filter(name__in=["Silver", "Gold", "Platinum"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_membershiptier_profile_membership_tier'),
    ]

    operations = [
        migrations.RunPython(seed_tiers, unseed_tiers),
    ]
