# Generated by Django 5.2.6 on 2025-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_seed_membership_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='api_base',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='country',
            name='provider_code',
            field=models.CharField(blank=True, help_text='internal provider key for adapter lookup', max_length=80),
        ),
    ]
