# Generated by Django 5.2.6 on 2025-10-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_deliveryaddress_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consoleshipment',
            name='uniq_shipment_action',
        ),
        migrations.RemoveField(
            model_name='consoleshipment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consoleshipment',
            name='shipment',
        ),
        migrations.RemoveIndex(
            model_name='consolidation',
            name='customer_co_user_id_23abf8_idx',
        ),
        migrations.RemoveField(
            model_name='consolidation',
            name='selected_courier',
        ),
        migrations.RemoveField(
            model_name='consolidation',
            name='selected_rate',
        ),
        migrations.RemoveField(
            model_name='consolidation',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='consolidationitem',
            name='uniq_consolidation_shipment',
        ),
        migrations.RemoveIndex(
            model_name='consolidationitem',
            name='customer_co_consoli_59e7ce_idx',
        ),
        migrations.RemoveField(
            model_name='consolidationitem',
            name='consolidation',
        ),
        migrations.RemoveField(
            model_name='consolidationitem',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ConsoleShipment',
        ),
        migrations.DeleteModel(
            name='Consolidation',
        ),
        migrations.DeleteModel(
            name='ConsolidationItem',
        ),
    ]
