# Generated by Django 5.2.6 on 2025-10-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_shipmentconsoleaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentConsoleAction',
        ),
    ]
