# Generated by Django 5.2.6 on 2025-10-13 06:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models, connection


def create_consolidation_table_if_not_exists(apps, schema_editor):
    """Create Consolidation table only if it doesn't already exist."""
    table_name = 'customer_consolidation'
    if table_name not in connection.introspection.table_names():
        # Table doesn't exist, create it
        with connection.schema_editor() as schema_editor_inner:
            model = apps.get_model('customer', 'Consolidation')
            schema_editor_inner.create_model(model)


def create_consolidationitem_table_if_not_exists(apps, schema_editor):
    """Create ConsolidationItem table only if it doesn't already exist."""
    table_name = 'customer_consolidationitem'
    if table_name not in connection.introspection.table_names():
        # Table doesn't exist, create it
        with connection.schema_editor() as schema_editor_inner:
            model = apps.get_model('customer', 'ConsolidationItem')
            schema_editor_inner.create_model(model)


def create_consoleshipment_table_if_not_exists(apps, schema_editor):
    """Create ConsoleShipment table only if it doesn't already exist."""
    table_name = 'customer_consoleshipment'
    if table_name not in connection.introspection.table_names():
        # Table doesn't exist, create it
        with connection.schema_editor() as schema_editor_inner:
            model = apps.get_model('customer', 'ConsoleShipment')
            schema_editor_inner.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_delete_shipmentconsoleaction'),
        ('warehouse', '0029_alter_consolidation_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            create_consolidation_table_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_consolidationitem_table_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_consoleshipment_table_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
