# Generated by Django 5.2.6 on 2025-10-15 09:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_consolidation_consolidationitem_consoleshipment_and_more'),
        ('warehouse', '0029_alter_consolidation_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_number', models.CharField(max_length=32, unique=True)),
                ('total_cbm', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('total_volume_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_gross_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('chargeable_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('shipments_count', models.PositiveIntegerField(default=0)),
                ('selected_courier_name', models.CharField(blank=True, max_length=128, null=True)),
                ('original_shipments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
