# Generated by Django 5.2.6 on 2025-10-15 09:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_consolidation_consolepackage_consolidationitem_and_more'),
        ('warehouse', '0029_alter_consolidation_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolepackage',
            options={},
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='chargeable_weight',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='original_shipments',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='selected_courier_name',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='shipments_count',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='suit_number',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='total_cbm',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='total_gross_weight',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='total_volume_weight',
        ),
        migrations.RemoveField(
            model_name='consolepackage',
            name='user',
        ),
        migrations.CreateModel(
            name='Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cbm', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('total_volume_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_gross_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('chargeable_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('chargeable_basis', models.CharField(default='volume', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('shipments_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('selected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_consolidations', to='warehouse.courier')),
                ('selected_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_consolidations', to='customer.courierrate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.consolidation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_items', to='warehouse.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hold', 'Hold'), ('release', 'Release'), ('packed', 'Packed'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('problem', 'Problem / Exception'), ('cancelled', 'Cancelled')], db_index=True, max_length=32)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_shipments', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_entries', to='warehouse.shipment')),
            ],
            options={
                'verbose_name': 'Console Shipment Action',
                'verbose_name_plural': 'Console Shipment Actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipment', 'action'], name='customer_co_shipmen_c991a3_idx'), models.Index(fields=['created_at'], name='customer_co_created_b41e93_idx')],
                'constraints': [models.UniqueConstraint(fields=('shipment', 'action'), name='uniq_shipment_action')],
            },
        ),
        migrations.AddIndex(
            model_name='consolidation',
            index=models.Index(fields=['user', 'created_at'], name='customer_co_user_id_23abf8_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidation',
            index=models.Index(fields=['status'], name='customer_co_status_8146d6_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationitem',
            index=models.Index(fields=['consolidation'], name='customer_co_consoli_59e7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationitem',
            index=models.Index(fields=['shipment'], name='customer_co_shipmen_baf46b_idx'),
        ),
        migrations.AddConstraint(
            model_name='consolidationitem',
            constraint=models.UniqueConstraint(fields=('consolidation', 'shipment'), name='uniq_consolidation_shipment'),
        ),
    ]
