# Generated by Django 5.2.6 on 2025-10-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_alter_consolepackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolepackage',
            name='consolidation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='console_package', to='customer.consolidation'),
        ),
    ]
