# Generated by Django 5.2.6 on 2025-10-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_consolepackage_consolidation'),
        ('warehouse', '0030_courier_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='consolidation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='customer.consolidation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='consolidation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='customer.consolidation'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='warehouse.shipment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='warehouse.shipment'),
        ),
    ]
