# Generated by Django 5.2.6 on 2025-10-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_deliveryaddress_consolidation_payment_consolidation_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS customer_consolepackage;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
