# Generated by Django 5.2.6 on 2025-10-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_drop_consolepackage_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsolePackage',
        ),
    ]
